Working on hello microverse project
shimels1/hello_microverse pull request #3
Opened 2023-07-04 16:22 UTC by shimels1

Updating previous code review comments.

2023-07-04 16:42 UTC, skyv26 requested changes
## Hi @shimels1, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGY3ODc1OTc1N2UzYjdhOGVkNzExZWUyNjk4NmIxNmNkNDJjOGNlMSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/z3piokwf0WPH81MOhu/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 

## Required Changes ♻️

- [ ] Well done 👏🏻 , you did an awesome job by implementing the changes as per the previous code reviewer's request but it seems like you still have to fix some issues. As mentioned by your previous code reviewer, there is a merge conflict between this branch and the main branch and need to resolve that before requesting another review. Here is an [article and a video ](https://www.freecodecamp.org/news/resolve-merge-conflicts-in-git-a-practical-guide/) suggestion on how you can go about that if you need help.

### Problem
![image](https://github.com/shimels1/hello_microverse/assets/66476329/19c3127e-eb97-460f-abdb-55a3c09f839e)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 16:42 UTC, skyv26 commented on README.md
> +
- [OPTIONAL] Please remove the placeholder or comment from your `README.md` file. These comments or placeholders are just meant for guidance purposes while creating `documentation` of your project not for users to see.

2023-07-04 16:42 UTC, skyv26 commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Please fix the typo here, your license file is `MIT.md` not `LICENSE`, because of the wrong path, your license is not opening if any person clicks on the README mit link.

2023-07-05 07:40 UTC, closed without merging

2023-07-05 07:41 UTC, shimels1 commented
done